name: Cleanup old GHCR packages

on:
  schedule:
    # Läuft jeden Tag um 03:00 Uhr nachts
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  clean-ghcr:
    runs-on: ubuntu-latest

    steps:
      - name: Delete old Docker Snapshot Images
        uses: snok/container-retention-policy@v3.1.0
        with:
          account-type: personal
          account: ${{ github.repository_owner }} # Dein Benutzername oder Org-Name
          image-names: cable-editor
          # Löscht nur die Tags, die mit "sha-" anfangen
          image-tags: "sha-*"
          cut-off: 7d # Älter als 7 Tage
          keep-n-most-recent: 3 # Die 3 neuesten behalten
          token: ${{ secrets.GHCR_PAT }}

      - name: Delete old Helm Snapshot Charts
        uses: snok/container-retention-policy@v3.1.0
        with:
          account-type: personal
          account: ${{ github.repository_owner }}
          image-names: cable-editor-chart
          # Löscht nur Tags, die "-snapshot." beinhalten
          image-tags: "*-snapshot.*"
          cut-off: 7d
          keep-n-most-recent: 3
          token: ${{ secrets.GHCR_PAT }}